changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
      - need more info
      - backlog
      - blocked
    authors:
      - dependabot
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
        - github_actions
        - java