name: Build the android APK
permissions:
  contents: read
on:
  push:
    branches:
      - main
      - prod

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAIN_PROJECT_MODULE: app
  APK_FILE_NAME: UmihiMusic
  STORE_FILE: release-key.jks
  BETA_TAG: beta

jobs:
  build-android-apk:
    permissions:
      packages: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Set up Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > ${{env.MAIN_PROJECT_MODULE}}/${{ env.STORE_FILE }}
        env:
          KEYSTORE_BASE64: ${{ secrets.SIGNING_KEY }}

      - name: Create keystore.properties file
        run: |
          echo "storeFile=${{ env.STORE_FILE }}" > keystore.properties
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Build APKs
        run: |
          if [[ "${{ github.ref_name }}" == "prod" ]]; then
            ./gradlew \
              assembleStandaloneRelease \
              assembleStoreRelease \
              -Pbeta=false \
              -PgitHash=${{ github.sha }}
          else
            ./gradlew \
              assembleStandaloneRelease \
              -Pbeta=true \
              -PgitHash=${{ github.sha }}
          fi

      - name: Collect APKs
        run: |
          mkdir -p release-apks

          cp app/build/outputs/apk/standalone/release/${{env.APK_FILE_NAME}}.apk \
            release-apks/${{env.APK_FILE_NAME}}.apk

          if [[ "${{ github.ref_name }}" == "prod" ]]; then
            cp app/build/outputs/apk/store/release/${{env.APK_FILE_NAME}}-store.apk \
              release-apks/${{env.APK_FILE_NAME}}-store.apk
          fi

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: apk-files
          path: release-apks/
          overwrite: true
          if-no-files-found: error
  update-beta-prerelease:
    permissions:
      packages: write
      contents: write
    if: github.ref_name != 'prod'
    needs:
      - build-android-apk
    runs-on: ubuntu-latest
    name: Update the beta GitHub release
    steps:
      - uses: actions/checkout@v7

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts

      - name: Delete Old Beta Release
        run: gh release delete ${{ env.BETA_TAG }} --cleanup-tag -y || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new Beta release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.BETA_TAG }}
          name: Beta
          artifacts: ./artifacts/**/*.apk
          allowUpdates: true
          removeArtifacts: true
          generateReleaseNotes: false
          body: ${{ github.event.head_commit.message }}
          makeLatest: false
          prerelease: true
          draft: false
          commit: ${{ github.sha }}

  publish-github-release:
    permissions:
      packages: write
      contents: write
    if: github.ref_name == 'prod'
    needs:
      - build-android-apk
    runs-on: ubuntu-latest
    name: Publish the GitHub release
    steps:
      - uses: actions/checkout@v7

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts
      - name: Extract version
        id: get_version
        run: |
          versionMajor=$(grep -oP 'val\s+versionMajor\s*=\s*\K[0-9]+' ${{ env.MAIN_PROJECT_MODULE }}/build.gradle.kts)
          versionMinor=$(grep -oP 'val\s+versionMinor\s*=\s*\K[0-9]+' ${{ env.MAIN_PROJECT_MODULE }}/build.gradle.kts)
          versionPatch=$(grep -oP 'val\s+versionPatch\s*=\s*\K[0-9]+' ${{ env.MAIN_PROJECT_MODULE }}/build.gradle.kts)

          version="${versionMajor}.${versionMinor}.${versionPatch}"

          echo "version=$version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create a Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ steps.get_version.outputs.version }}
          commit: prod
          artifacts: ./artifacts/**/*.apk
          generateReleaseNotes: false
          draft: true
          body: |
            ## Release v${{ steps.get_version.outputs.version }}
            
            ### Features
            - 
            
            ### Bug fixes
            - 
            
            ### Full Changelog
            https://github.com/ilianoKokoro/umihi-music/compare/v${{ steps.get_version.outputs.version }}...v${{ steps.get_version.outputs.version }}
            
