name: Crowdin Contributors Action
permissions:
    contents: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 */12 * * *"
    workflow_dispatch:

env:
    BRANCH: "crowdin-readme"

jobs:
    crowdin-contributors:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Generate Crowdin Contributors table
              uses: andrii-bodnar/action-crowdin-contributors@v3
              with:
                  contributors_per_line: 5
                  max_contributors: 50
                  image_size: 48
                  min_words_contributed: 1
                  include_languages: true
              env:
                  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

            - name: Reset ${{env.BRANCH}} branch
              run: |
                  git checkout -B ${{env.BRANCH}}

            - uses: EndBug/add-and-commit@v10
              with:
                  default_author: github_actions
                  message: "docs: update Crowdin contributors"
                  new_branch: ${{env.BRANCH}}
                  push: "--force origin ${{env.BRANCH}}"
